version: '3.8'

services:
  server:
    build: ./server
    container_name: server 
    ports:
      - "3001:3001"
    environment: 
      - mongodb+srv://prasunachandrika156:9LryQernxuYOB8Dd@cluster0.lt45cda.mongodb.net/
  client:
    build: ./client
    container_name: client
    ports :
    - "3000:80"